### ISSUE TITLE
Some packages install failed

### ISSUE THREAD

**Issue by vhtq18w** [kiennq/scoop-misc#1]
These package will fail to install.
* emax64
* emacs-snapshot

Error message
```
Creating shim for 'runemacs'.
Can't shim 'bin\runemacs.exe': File doesn't exist.
```

I checked the installation directory(%SCOOP%/apps/$package-name/) and found it was empty.
But it can be sure that the compressed package has been successfully downloaded.

**Comment by kiennq** [comment]
It seems due to 7zip installation issue lukesampson/scoop#3346
Can you try to remove 7zip and install the emacs packages again? It will use poweshell command to extract instead

**Comment by vhtq18w** [comment]
It maybe `"extract_dir"` argument problem?
I remove `"extract_dir"` and `"env_set"`, it works fine.
My modified json is at [emacs-snapshot.json](https://github.com/vhtq18w/brsucket/blob/master/bucket/emacs-snapshot.json)

**Comment by kiennq** [comment]
Possibly, I will remove `extract_dir` then.

**Comment by kiennq** [comment]
Removed with af41e89
