### ISSUE TITLE
[Request] Add Emacs 28.2 (or any latest stable release) with native compilation support

### ISSUE THREAD

**Issue by FROST8ytes** [kiennq/scoop-misc#11]
I realize that `emacs-k` provides this, but some emacs frameworks, i.e. doom, does not support pre-release versions of emacs. I am able to be the maintainer, as long as I get guidance from @kiennq 😃

**Comment by kiennq** [comment]
I believe the Emacs 28.2 that you got from GNU release should already have native compilation support, however, you will need [msys2](https://www.msys2.org/) and [libgccjit](https://packages.msys2.org/package/mingw-w64-x86_64-libgccjit?repo=mingw64) installed to be able to do native compiling for new elisp code.

Alternatively, you can use https://github.com/kiennq/emacs-build to build your own stable Emacs release that support native compilation with all of the dependencies included.
See the repo's Github action for more information about which commands you should run
