### ISSUE TITLE
libtree-sitter-toml.dll missing from emacs-k builds

### ISSUE THREAD

**Issue by dertuxmalwieder** [kiennq/scoop-misc#12]
FYI:

> Warning (treesit): Cannot activate tree-sitter, because language grammar for toml is unavailable (not-found): (libtree-sitter-toml libtree-sitter-toml.dll) No such file or directory

**Comment by kiennq** [comment]
Please install the dll by your own, the tree sitter parsers are not a part of Emacs.
You can get them from https://github.com/kiennq/treesit-langs
