### ISSUE TITLE
emacs-kl can not load emacs-rime module

### ISSUE THREAD

**Issue by jinzhongjia** [kiennq/scoop-misc#17]
The module can be compiled successfully, but cannot be loaded.
Preliminary speculation may be that a certain dynamic link library related to dynamic modules is missing.
https://github.com/DogLooksGood/emacs-rime

**Comment by kiennq** [comment]
I'm sorry but you will have to investigate more on why it can't be loaded with rime module. The native comp and treesit is working fine so dynamic module should be working as well.

**Comment by JordanAnthonyKing** [comment]
I've been using the emacsk package for quite a while, what's the difference with the kl package?

**Comment by jinzhongjia** [comment]
To be honest, I can't find the reason why rime cannot be loaded, and I don't know if this issue should be closed
@kiennq
