### ISSUE TITLE
emacs-k (MPS): needs scoop shims

### ISSUE THREAD

**Issue by garyo** [kiennq/scoop-misc#19]
I just tried `scoop install emacs-k` and noticed it doesn't include the shims for `emacs.exe` and `runemacs.exe`. Perhaps copy the shortcut setup code from `emacs-kl` at https://github.com/kiennq/scoop-misc/blob/c79abee0f5f6e8fea87ca45326533101ffc87dda/bucket/emacs-kl.json#L35?

**Comment by kiennq** [comment]
It doesn't need shortcuts as the msix package is installed (so it's only compatible with Windows 11) and create a shim under `%localappdata%\microsoft\windowsapp` already. That path should also be in the Windows PATH by default as well.
For Windows 10 and before, the package to use is `emacs-kl`

**Comment by garyo** [comment]
Ah, I see. I noticed the kl package is also a msix but does have the shortcuts so I was just confused. I was expecting since I install it via `scoop` that it would put something in the usual scoop shims place. Thanks!
