### ISSUE TITLE
emacs-snapshot@28.0.50-snapshot-2020-06-26: download via aria2 failed

### ISSUE THREAD

**Issue by BibleBelt** [kiennq/scoop-misc#3]
Looks like another snapshot has appeared, breaking the download.

Installing 'emacs-snapshot' (28.0.50-snapshot-2020-06-26) [64bit]
Starting download with aria2 ...
Download: [#538d29 0B/0B CN:1 DL:0B]
Download: 07/06 13:15:55 [ERROR] CUID#8 - Download aborted. URI=https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-28/emacs-28.0.50-snapshot-2020-06-26-x86_64.zip
Download: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-28/emacs-28.0.50-snapshot-2020-06-26-x86_64.zip
Download:   -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 538d29|ERR |       0B/s|C:/Users/xtp/scoop/cache/emacs-snapshot#28.0.50-snapshot-2020-06-26#https_alpha.gnu.org_gnu_emacs_pretest_windows_emacs-28_emacs-28.0.50-snapshot-2020-06-26-x86_64.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 3) Resource was not found
ERROR https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-28/emacs-28.0.50-snapshot-2020-06-26-x86_64.zip
    referer=https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-28/
    dir=C:\Users\xtp\scoop\cache
    out=emacs-snapshot#28.0.50-snapshot-2020-06-26#https_alpha.gnu.org_gnu_emacs_pretest_windows_emacs-28_emacs-28.0.50-snapshot-2020-06-26-x86_64.zip

ERROR & 'C:\Users\xtp\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\xtp\scoop\cache\emacs-snapshot.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=22448 --continue

**Comment by kiennq** [comment]
Updated with  925da23.
Thanks for letting me know

**Comment by BibleBelt** [comment]
Great. Thanks a lot.
