### ISSUE TITLE
emacs-snapshot@28.0.91: hash check failed

### ISSUE THREAD

**Issue by AusCyberman** [kiennq/scoop-misc#5]
App:         scoop-misc-lol/emacs-snapshot
URL:         https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-28/emacs-28.0.91.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    4ad06be9a6fb3ffed476db10901690ed256ee14e8c0b06019e209e48c344fe70
Actual:      afc3ee40eb282f08821188fde1c37aea6d28e6bbfe28daed9d22ee13d7123abe

**Comment by kiennq** [comment]
Thanks for noticing me, updated with 0660028bc68785afe6d2a43f209a797f038366de
